name: map_launcher_web
description: Web implementation of the map_launcher plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: map_launcher
    platforms:
      web:
        pluginClass: MapLauncherWeb
        fileName: map_launcher_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  map_launcher_platform_interface:
    path: ../map_launcher_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
